WIP - docs: Document SQL action
chutney-testing/chutney-testing.github.io pull request #28
Opened 2022-10-14 08:49 UTC by bessonm

2022-10-14 11:26 UTC, bessonm commented on docs/actions/sql.md
> +* `columns`: Returns a list of [Columns](#column) (List< Column >).
I couldn't find how to properly escape `<>` in a bullet list :/
might needs a look in the python md/html generator if someone is up for a contribution there :)

2022-10-17 12:24 UTC, nbrouand requested changes

2022-10-18 12:52 UTC, bessonm commented on docs/actions/sql.md
> +!!! important "Database URL"
done

2022-10-18 13:10 UTC, bessonm commented
2 notes: 
* I choose to do a collapsible example for the configuration example
* I choose to put the Logging results admonition with the "inputs" tab

Tell me what you think ?

2022-10-18 14:53 UTC, nbrouand commented
> 2 notes:
> 
>     * I choose to do a collapsible example for the configuration example
> 
>     * I choose to put the Logging results admonition with the "inputs" tab
> 
> 
> Tell me what you think ?
Sorry but i dont like these. I was going to make a comment about these before seeing your comments :)
I prefer to have the example opened by default.
I was confused when i click on output. I prefer to not hide blocks when cliking on output

2022-10-18 14:55 UTC, bessonm commented
> 

All right, I wasn't sure so I asked.
I'll change that

2022-10-19 09:34 UTC, nbrouand approved these changes

2022-10-19 09:34 UTC, merged