docs(action): MongoDB documentation
chutney-testing/chutney-testing.github.io pull request #34
Opened 2022-11-15 16:34 UTC by bessonm

2022-11-16 09:41 UTC, nbrouand commented on docs/actions/mongo.md
> +    For all actions, the target should have a property `databaseName`
please provide a target example as others

2022-11-16 11:20 UTC, bessonm commented on docs/actions/mongo.md
> +    For all actions, the target should have a property `databaseName`
done

2022-11-17 13:57 UTC, nbrouand requested changes

2022-11-17 13:57 UTC, nbrouand commented on docs/actions/mongo.md
> +    query = "my query"
for all queries, you could set a real mongodb query, for example :
collection = "ghibli_movies",
query = "{ name: { $in: [ 'Pom Poko', 'Spirited Away' ] } }"

2022-11-17 13:57 UTC, nbrouand commented on docs/actions/mongo.md
> +
Specify what it lists

2022-11-17 13:57 UTC, nbrouand commented on docs/actions/mongo.md
> +    document = "my document"
same as query for all document/update fields: 
```
document = """
{
    id: "123456",
    title: "My Neighbor Totoro",
    original_title: "となりのトトロ",
    original_title_romanised: "Tonari no Totoro",
    description: "Two sisters move to the country with their father in order to be closer to their hospitalized mother, and discover the surrounding trees are inhabited by Totoros, magical spirits of the forest. When the youngest runs away from home, the older sister seeks help from the spirits to find her.",
    director: "Hayao Miyazaki",
    producer: "Hayao Miyazaki",
    release_date: 1988,
    running_time: 86,
}
"""

2022-11-17 13:57 UTC, nbrouand commented on docs/actions/mongo.md
> +    |          | `arrayFilters` | List<String\> |         |
specify only since @3.5.12 mongodb version

2022-11-23 15:10 UTC, nbrouand approved these changes

2022-11-23 18:28 UTC, KarimGl approved these changes

2022-11-24 15:40 UTC, merged